# syntax=docker/dockerfile:1
FROM --platform=linux/arm64 alpine:3.20
RUN --mount=type=cache,target=/var/cache/apk,sharing=locked \
    apk add --no-cache build-base cmake pkgconf git alsa-lib-dev lilv-dev lv2-dev linux-headers eudev-dev
