[audio]
sample_rate = 48000
block_size  = 64
channels    = 1
instrument_device = hw:0,0
instrument_device_match = AIR 192
audio_device = hw:UAC2Gadget,0

[cores]
home_fx     = 1
user_fx     = 3

[rt]
audio_priority = 95

[effects]
home_dir = /effects/home
user_dir = /effects/user
resonode_dir = /effects/resonode
pitchtracker_dir = /effects/pitchtracker
# disable_core3_lv2 = 1

[link]
enabled  = true

[wifi]
ap_ssid  = ticker

[midi]
midi_device = auto

[remote]
token = d5c3612a6c60271d47961bdfaea9f379

[storage]
usb_record = true
usb_mount_point = /media/aloop-usb
usb_chunk_minutes = 10
usb_chunk_count = 6
